spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    alicloud:
      access-key: LTAI5tEec77k8ES54VCqN8BL
      secret-key: mhTaADAdxty9l7ZWwt3JMefmgeu2RA
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-sx1024

      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        skin: 1
        sign: 1
        appcode: bbab427348094a8ea8dda5c0f8f43597

  application:
    name: gulimall-third-party

server:
  port: 30000
